
services:
  movies:
    image: uprightbalance/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: uprightbalance/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: uprightbalance/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: uprightnalance/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
